### ISSUE TITLE
buyMultiple

### ISSUE THREAD

**Issue by artman325** [Intercoin/NonFungibleTokenContract#34]
can you put this functionality in NFT 2 contract directly
just have buyMultiple(tokenIds, address) payable
and buyMultiple(tokenIds, address, currency, amount)

**Comment by EGreg** [comment]
Let’s just change existing buy() methods to accept array of tokenIds always, instead of individual tokenId. And the currency and amounts would match the total.

Then you would loop through the array and call buy() on each one. Simple. At the end, verify that the amount in params matches what was sent. Also revert if currency in one of the tokenSaleInfo is different.

**Comment by artman325** [comment]
closed 
see #39
