### ISSUE TITLE
Please rename variable `beneficiary` to `owner` to be more clear

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#59]
Right here in this function: https://github.com/Intercoin/NonFungibleTokenContract/blob/main_hardhat/contracts/v2/NFTState.sol#L430

everywhere else it is called `owner` referring to owner of NFT.
Yes they are also beneficiary of a payment, but it's clearer

**Comment by artman325** [comment]
seems it would be more complicated to understand what is what.
if will rename to `owner` any reviewer will ask:"what's owner do you means here? nft-owner, or contract's owner?"
then he will go into [_getTokenSaleInfo](https://github.com/Intercoin/NonFungibleTokenContract/blob/300e1edb36adff52b322cef750d68c656ba101ea/contracts/v2/NFTStorage.sol#L312) and discover that this `owner` can be series.author. 
wow. ok. but if series author is an owner than he can transfer token to some1, and he can't do it). because token have not exists yet. and `ownerOf` will rejected with `"ERC721: owner query for nonexistent token"`.

**Сonclusion** 
in the scope of `buy` method it's exactly `beneficiary` but not `owner`. 
More clearly will be called like this
`some_person_who_will_get_commission_payments_after_sell_this_token_to_sender`
It doesn't have to be an owner. Just address that will return `_getTokenSaleInfo` method

Please confirm that it's really need to do that
