### ISSUE TITLE
Hooks for lock and unlock

### ISSUE THREAD

**Issue by EGreg** [Intercoin/NonFungibleTokenContract#69]
In NFT 1.0 use `pushTokenTransferHook` but in NFT 2.0 build the following six functions in:

`portfolioLock(custodian)` // called by owner of token or revert
`portfolioUnlock(owner)` // called by custodian, silently succeeds
`portfolioCustodian(owner)` // may return 0 or custodian address

`lock( [tokenIds], custodian )` // skip silently if any token already locked, even to another custodian
`unlock( [ tokenIds] )`  // custodian can call this with a subset of any locked tokens… silently skip any tokens which were not locked
`custodian(tokenId)` // returns 0 or custodian address

**Comment by EGreg** [comment]
Is this done? @artman325

**Comment by artman325** [comment]
Please answer to questions:
Q1: what definitely do these methods:
portfolioLock(custodian)
portfolioUnlock(owner)
portfolioCustodian(owner)


for example 
method `lock( [tokenIds], custodian )` called by owner of `tokenIds` and freeze these tokens to custodian.

Q2: What is portfolio(in ERC721 env) ?
Q3: if token locked, it can not be transferable. What happens when custodian will unlock such token? token's owner will still the same?

**Comment by EGreg** [comment]
Q1: Same as the external lock contract does right now, just inside the NFT contract.

owner of token can lock it and name a custodian, still owns token but can’t transfer it

custodian then unlocks token allowing its owner to transfer it again

the custodian method is a view method that returns custodian of a token, if any

Q2: just a prefix of method names

Q3: yes, owner never changes

**Comment by artman325** [comment]
> NFT 2.0 build the following six functions 

> Q1: Same as the external lock contract does right now, just inside the NFT contract.

you said need to six functions. 
`lock` and `unlock` are already present in lockedhook contract
where i can find 
portfolioLock(custodian)
portfolioUnlock(owner)
portfolioCustodian(owner)
in https://github.com/Intercoin/NonFungibleTokenContract/blob/main_aliens/contracts/LockedHook.sol ?
if it's new methods so what definitely they will do?
